//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = module.exports = {};
var ReplyToExchange = module.exports.ReplyToExchange = function(args) {
  this.exchange = null;
  this.routingKey = null;
  if (args) {
    if (args.exchange !== undefined && args.exchange !== null) {
      this.exchange = args.exchange;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field exchange is unset!');
    }
    if (args.routingKey !== undefined && args.routingKey !== null) {
      this.routingKey = args.routingKey;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field routingKey is unset!');
    }
  }
};
ReplyToExchange.prototype = {};
ReplyToExchange.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.exchange = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.routingKey = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ReplyToExchange.prototype.write = function(output) {
  output.writeStructBegin('ReplyToExchange');
  if (this.exchange !== null && this.exchange !== undefined) {
    output.writeFieldBegin('exchange', Thrift.Type.STRING, 1);
    output.writeString(this.exchange);
    output.writeFieldEnd();
  }
  if (this.routingKey !== null && this.routingKey !== undefined) {
    output.writeFieldBegin('routingKey', Thrift.Type.STRING, 2);
    output.writeString(this.routingKey);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ReplyDestination = module.exports.ReplyDestination = function(args) {
  this.exchange = null;
  if (args) {
    if (args.exchange !== undefined && args.exchange !== null) {
      this.exchange = new ttypes.ReplyToExchange(args.exchange);
    }
  }
};
ReplyDestination.prototype = {};
ReplyDestination.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.exchange = new ttypes.ReplyToExchange();
        this.exchange.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ReplyDestination.prototype.write = function(output) {
  output.writeStructBegin('ReplyDestination');
  if (this.exchange !== null && this.exchange !== undefined) {
    output.writeFieldBegin('exchange', Thrift.Type.STRUCT, 1);
    this.exchange.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ReplyParameters = module.exports.ReplyParameters = function(args) {
  this.taskId = null;
  this.replyTo = null;
  this.passThrough = null;
  if (args) {
    if (args.taskId !== undefined && args.taskId !== null) {
      this.taskId = args.taskId;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field taskId is unset!');
    }
    if (args.replyTo !== undefined && args.replyTo !== null) {
      this.replyTo = new ttypes.ReplyDestination(args.replyTo);
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field replyTo is unset!');
    }
    if (args.passThrough !== undefined && args.passThrough !== null) {
      this.passThrough = args.passThrough;
    }
  }
};
ReplyParameters.prototype = {};
ReplyParameters.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.taskId = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.replyTo = new ttypes.ReplyDestination();
        this.replyTo.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.passThrough = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ReplyParameters.prototype.write = function(output) {
  output.writeStructBegin('ReplyParameters');
  if (this.taskId !== null && this.taskId !== undefined) {
    output.writeFieldBegin('taskId', Thrift.Type.STRING, 1);
    output.writeString(this.taskId);
    output.writeFieldEnd();
  }
  if (this.replyTo !== null && this.replyTo !== undefined) {
    output.writeFieldBegin('replyTo', Thrift.Type.STRUCT, 2);
    this.replyTo.write(output);
    output.writeFieldEnd();
  }
  if (this.passThrough !== null && this.passThrough !== undefined) {
    output.writeFieldBegin('passThrough', Thrift.Type.STRING, 3);
    output.writeString(this.passThrough);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Empty = module.exports.Empty = function(args) {
};
Empty.prototype = {};
Empty.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Empty.prototype.write = function(output) {
  output.writeStructBegin('Empty');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

