//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


declare class CourseDetails {
  name: string;
  description: string;
  longDescription: string;
  imageUrl: string;
  tags: string[];

  constructor(args?: { name: string; description?: string; longDescription?: string; imageUrl?: string; tags?: string[]; });
}

declare class Course {
  id: string;
  details: CourseDetails;
  moduleIds: string[];

  constructor(args?: { id: string; details: CourseDetails; moduleIds: string[]; });
}
