//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


declare class ModuleDetails {
  name: string;
  description: string;
  longDescription: string;
  imageUrl: string;
  tags: string[];

  constructor(args?: { name: string; description?: string; longDescription?: string; imageUrl?: string; tags?: string[]; });
}

declare class Module {
  id: string;
  details: ModuleDetails;
  units: ModuleUnit[];

  constructor(args?: { id: string; details: ModuleDetails; units?: ModuleUnit[]; });
}
