//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


declare class GetCourseResult {
  courses: Course[];
  modules: { [k: string]: Module; };

  constructor(args?: { courses: Course[]; modules?: { [k: string]: Module; }; });
}

declare class UpdateCourseDetails {
  name: string;
  description: string;
  longDescription: string;
  imageUrl: string;
  tags: string[];

  constructor(args?: { name?: string; description?: string; longDescription?: string; imageUrl?: string; tags?: string[]; });
}

declare class UpdateModuleDetails {
  name: string;
  description: string;
  longDescription: string;
  imageUrl: string;
  tags: string[];

  constructor(args?: { name?: string; description?: string; longDescription?: string; imageUrl?: string; tags?: string[]; });
}

declare class UpdateUnitDetails {
  name: string;
  description: string;
  imageUrl: string;

  constructor(args?: { name?: string; description?: string; imageUrl?: string; });
}

declare class ChangeStackVersionInUnitResult {
  unitVersion: UnitVersion;

  constructor(args?: { unitVersion?: UnitVersion; });
}

declare class NotFoundException extends Thrift.TException {
}

declare class ReorderConflictException extends Thrift.TException {
  currentModule: Module;

  constructor(args?: { currentModule: Module; });
}
