//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


declare class UnitDetails {
  name: string;
  description: string;
  imageUrl: string;

  constructor(args?: { name: string; description?: string; imageUrl?: string; });
}

declare class UnitVersion {
  id: string;
  stackVersionId: string;

  constructor(args?: { id: string; stackVersionId: string; });
}

declare class ModuleUnit {
  id: string;
  details: UnitDetails;
  versions: UnitVersion[];

  constructor(args?: { id: string; details: UnitDetails; versions?: UnitVersion[]; });
}
